force-app/main/default/objects/reddit_items__c/reddit_items__c.object-meta.xml
<CustomObject>
    <label>reddit_item</label>
    <nameField>
        <label>reddit_item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>reddit_items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/reddit_items__c/fields/author_fullname__c.field-meta.xml
<CustomField>
    <fullName>author_fullname__c</fullName>
    <label>author_fullname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/gilded__c.field-meta.xml
<CustomField>
    <fullName>gilded__c</fullName>
    <label>gilded</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/saved__c.field-meta.xml
<CustomField>
    <fullName>saved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>saved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/selftext__c.field-meta.xml
<CustomField>
    <fullName>selftext__c</fullName>
    <label>selftext</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/subreddit__c.field-meta.xml
<CustomField>
    <fullName>subreddit__c</fullName>
    <label>subreddit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/HttpCalloutredditems_20230512005753.cls
/**
 * @Clase       :HttpCalloutredditems
 * @author            : Marco Alavez
 * @group             : Xcaret
 * @last modified on  : 05-12-2023
 * @last modified by  : Marco Alavez
**/
public with sharing class HttpCalloutredditems {
    //Creamos variables staticas para parametros del HTTP
    public static final String URL ='https://www.reddit.com/r/subreddit/new.json?sort=new';
    public static final String GET ='GET';

    /*  Metodo para hacer el llamado del HTTP y guardar datos en Objeto 	reddit_items__c
        Se va ejecutar como apex anonimo desde la consola
    */
    public static List<Reddis_Util.Data> getReddisData(){
        List<Reddis_Util.Data> reddisData = New List<Reddis_Util.Data>();
        List<reddit_items__c> itemsData = New List<reddit_items__c>();

        try {

            Http h = New Http();
            HttpRequest req = New HttpRequest();
            req.setEndpoint(URL);
            req.setMethod(GET);
            req.setTimeout(60000);

            //Ejecutamos solicitud de servicio

            HttpResponse redditResponse = h.send(req);
            Reddis_Util reddtPostResponse = Reddis_Util.parse(redditResponse.getBody());
            List<Reddis_Util.Children> redditPosts = reddtPostResponse.data.children;

            // Iteramos datos hijos y los guardamos en la lista para insertar en Objeto reddit_items__c
            for(Reddis_Util.Children child : redditPosts){
                reddisData.add(child.data);
            }

            // Iniciamos casteo de campos para insertar en el objeto reddit_items__c
            for(Reddis_Util.Data data : reddisData){
                reddit_items__c redditem = new reddit_items__c();
                redditem.subreddit__c = data.subreddit;
                redditem.selftext__c = data.selftext;
                redditem.author_fullname__c = data.author_fullname;
                redditem.saved__c = data.saved;
                redditem.gilded__c = data.gilded;


            }

            System.debug('#### reddisData ' + reddisData);

        } catch (Exception e) {
            System.debug('#### Exception ' + e.getMessage());
        }

        //Ejecutamos una prueba antes de insertar registros para validar que todo se esta ejecutando correctamente

        return reddisData;
    }



}