force-app/main/default/objects/reddit_items__c/reddit_items__c.object-meta.xml
<CustomObject>
    <label>reddit_item</label>
    <nameField>
        <label>reddit_item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>reddit_items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/reddit_items__c/fields/author_fullname__c.field-meta.xml
<CustomField>
    <fullName>author_fullname__c</fullName>
    <label>author_fullname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/selftext__c.field-meta.xml
<CustomField>
    <fullName>selftext__c</fullName>
    <label>selftext</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/reddit_items__c/fields/thumbnail__c.field-meta.xml
<CustomField>
    <fullName>thumbnail__c</fullName>
    <label>thumbnail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

.history/force-app/main/default/classes/reddit_itemsController_20230512012646.cls
/**
 * @description       : reddit_itemsController
 * @author            : Marco Alavez
 * @group             : 
 * @last modified on  : 05-12-2023
 * @last modified by  : Marco Alavez
**/
public with sharing class reddit_itemsController {

    @AuraEnabled
    public static List<reddit_items__c> buscarreddit_items = new List<reddit_items__c>(){
        try {
            List<reddit_items__c> reddItemsList =[Select Id, title__c, author_fullname__c, thumbnail__c, selftext__c From reddit_items__c  Order by CreatedDate Asc];

            System.debug('#### reddItemsList ' + reddItemsList);
        } catch (Exception e) {
            System.debug('#### Exception ' +e.getMessage());
        }

        return reddItemsList;
    }




}